### ISSUE TITLE
Can't open 127.0.0.1:8080 from browser

### ISSUE THREAD

**Issue by MihaelIsaev** [idev4u/basic-swift-nio-http-server#1]
Hey, could you please give workaround how to make it answer correctly to browser? I want to run `wrk` benchmark to test swift-nio performance.

**Comment by idev4u** [comment]
Thanks for your request, let me check this. One question before. What kind of request you would like to test with `wrk` GET or POST?

**Comment by MihaelIsaev** [comment]
Thank you for quick response! I'd like to test simple GET reqeust.

**Comment by idev4u** [comment]
@MihaelIsaev I have update the Readme section, hopefully it helps you.
https://github.com/idev4u/basic-swift-nio-http-server/blob/master/README.md#benchmark

**Comment by MihaelIsaev** [comment]
@idev4u Thank you!
